export default function Dashboard(props: { className?: string }) {
  return (
    <svg
      className={props.className}
      stroke="currentColor"
      fill="currentColor"
      strokeWidth="0"
      viewBox="0 0 512 512"
      height="1em"
      width="1em"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect
        width="176"
        height="176"
        x="48"
        y="48"
        fill="none"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="32"
        rx="20"
        ry="20"
      ></rect>
      <rect
        width="176"
        height="176"
        x="288"
        y="48"
        fill="none"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="32"
        rx="20"
        ry="20"
      ></rect>
      <rect
        width="176"
        height="176"
        x="48"
        y="288"
        fill="none"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="32"
        rx="20"
        ry="20"
      ></rect>
      <rect
        width="176"
        height="176"
        x="288"
        y="288"
        fill="none"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="32"
        rx="20"
        ry="20"
      ></rect>
    </svg>
  );
}
