import "./globals.css";
import type { Metadata } from "next";
import { AuthProvider } from "./provider/Authprovider";

export const metadata: Metadata = {
  title: "Trading Journal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-200">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
